/// CodableConcept
Class FHIRTemplate.DataType.CodeableConcept Extends JSONTemplate.Base
{

/// JSON出力する際のテンプレート
XData Template [ MimeType = application/json ]
{
{
	"coding": [
		{
			"system": "#(..system)#",
			"code": "#(..code)#",
			"display": "#(..display)#"
		}
	],
	"text": "#(..text)#"
}
}

Property system As %String;

Property code As %String;

Property display As %String;

Property text As %String;

}
