/// 患者リソース
Class FHIRTemplate.Bundle Extends FHIRTemplate.Resource
{

/// JSON出力する際のテンプレート
XData Template [ MimeType = application/json ]
{
{
  "resourceType": "#(..#ResourceType)#",
  "meta": {
    "profile": [ "#(..#Profile)#" ]
  },
  "type": "document",
  "timestamp": "#(..TimeStamp)#",
  "entry": [
    "#(..Resource(FHIRTemplate.Bundle.entry))#"
      ],
  "signature": {
    "type":"a"
  }
  }
}

Parameter ResourceType = "Bundle";

Parameter Profile = "jpfhir.jp/fhir/eDischargeSummary/StructureDefinition/JP_Bundle_eDischargeSummary";

Property TimeStamp As FHIRTemplate.DataType.TimeStamp;

Property Resource As list Of Resource;

/// FHIRドキュメントの作成
ClassMethod CreateFHIRDocument(composition As Composition) As Bundle
{
  set obj=..%New()
  
  // bundleリソース管理クラスのインスタンスを取得
  set br=##class(FHIRTemplate.Util.BundleResource).%New()

  // 指定されたCompositionリソースから関連するリソースを取得
  do composition.GetResources(br)

  // 取得した関連リソースをBundleに登録
  do br.ExportResources(obj.Resources)
  quit obj
}

}
